name: Hasura DB Update

on:
  push:
    # branches:
    # - feature/**

jobs:
  update-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: moped
        ports:
          - 5432:5432
        # Set health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Start Hasura GraphQL Engine
        run: |
          docker run -d -p 8080:8080 \
            -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@localhost:5432/moped \
            -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
            hasura/graphql-engine:v2.37.0
