name: Hasura DB Update

on:
  push:
    # branches:
    # - feature/**

jobs:
  publish-views:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Set PostgreSQL environment variables
        run: |
          echo "PGHOST=localhost" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV
          echo "PGDATABASE=moped" >> $GITHUB_ENV
          echo "PGUSER=moped" >> $GITHUB_ENV
          echo "PGPASSWORD=moped" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: "Spin-up the DB stack"
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          cd ./moped-database;
          ./hasura-cluster setenv local;
          ./hasura-cluster start;

      - name: List all views in public schema excluding pattern
        run: |
          psql -A -t -c "SELECT table_name FROM information_schema.views WHERE table_schema = 'public';" | grep -v -E '^geo[a-zA-Z]+y_columns$' | \
          grep -v -E '^geo[a-zA-Z]+y_columns$'
